# Generated by Django 5.2 on 2025-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=20),
        ),
    ]
