# Generated by Django 5.2 on 2025-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marketing_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='termsandconditions_and_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
